workflows:
  ios-release:
    name: iOS Release Pipeline
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
