workflows:
  ios-release:
    name: iOS Release Pipeline
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Build iOS App and Create IPA
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          mv build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -qr app.ipa Payload
    artifacts:
      - build/ios/ipa/app.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
